Update action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -18,7 +18,7 @@ runs:
       shell: bash
       run: |
         if [[ -z "$PIPELINES_CLI_VERSION" ]]; then
-          echo "::error::pipelines-orchestrate >= v3 requires that PIPELINES_CLI_VERSION be set, this likely indicates that pipelines orchestrate was version-bumped without also updating pipelines-workflows." >&2
+          echo "::error::pipelines-orchestrate >= v3 requires that PIPELINES_CLI_VERSION be set, this likely indicates that pipelines orchestrate was version-bumped without also updating pipelines-workflows.  If you are not familiar with pipelines-workflows it likely means you are on an older version of pipelines and should either revert the version change of pipelines-orchestrate or reach out to support@gruntwork.io" >&2
           exit 1
         fi
 
